[package]
name = "Cryptography-and-cryptanalysis"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
regex = "1.11.3"
statrs = "0.18.0"
gcd = "2.3.0"
bare_metal_modulo = "1.2.5"
rayon = "1.11.0"
rand = "0.8.5"